// apps/frontend/src/app/dashboard/dashboard.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';

import { ButtonModule } from 'primeng/button';
import { AvatarModule } from 'primeng/avatar';
import { ProgressBarModule } from 'primeng/progressbar';
import { TagModule } from 'primeng/tag';
import { TooltipModule } from 'primeng/tooltip';
import { CardModule } from 'primeng/card';

interface StatCard {
  label: string;
  value: string;
  delta: string;
  deltaUp: boolean;
  deltaLabel: string;
}

interface QueueItem {
  id: string;
  page: string;
  project: string;
  errors: number;
  priority: 'High' | 'Medium' | 'Low' | 'Crit';
  prioritySeverity: 'danger' | 'warn' | 'info' | 'secondary';
}

interface RecentProject {
  id: string;
  name: string;
  progress: number;
}

interface ActivityItem {
  user: string;
  initials: string;
  avatarBg: string;
  action: string;
  target: string;
  time: string;
}

@Component({
  selector: 'app-dashboard',
  standalone: true,
  imports: [
    CommonModule,
    RouterModule,
    ButtonModule,
    AvatarModule,
    ProgressBarModule,
    TagModule,
    TooltipModule,
    CardModule,
  ],
  templateUrl: './dashboard.component.html',
  styleUrl: './dashboard.component.scss',
})
export class DashboardComponent {
  userName = 'Ravi';
  lastSync = '2 min ago';

  stats: StatCard[] = [
    { label: 'Active projects', value: '12', delta: '+2', deltaUp: true, deltaLabel: 'this month' },
    { label: 'Pages transl.', value: '1,240', delta: '+132', deltaUp: true, deltaLabel: 'this wk' },
    { label: 'Pending review', value: '350', delta: '−18', deltaUp: false, deltaLabel: 'since Mo' },
    { label: 'Avg quality', value: '82%', delta: '+4pts', deltaUp: true, deltaLabel: '' },
  ];

  throughputMetric = 'Pages'; // or 'Words'
  throughputPeak = 132;
  throughputAvg = 88;
  throughputTotal = 1061;
  
  // Mock data for 12 weeks of bars (values 0-100 for height %)
  throughputData = [65, 78, 45, 92, 85, 70, 95, 88, 92, 60, 85, 100];

  queueItems: QueueItem[] = [
    { id: '1', page: 'P45', project: "Pilgrim's Progress", errors: 3, priority: 'Medium', prioritySeverity: 'info' },
    { id: '2', page: 'P46', project: "Pilgrim's Progress", errors: 2, priority: 'Low', prioritySeverity: 'secondary' },
    { id: '3', page: 'P12', project: 'Don Quixote', errors: 8, priority: 'High', prioritySeverity: 'warn' },
    { id: '4', page: 'P78', project: '1984', errors: 15, priority: 'Crit', prioritySeverity: 'danger' },
    { id: '5', page: 'P23', project: 'The Alchemist', errors: 5, priority: 'Medium', prioritySeverity: 'info' },
  ];

  recentProjects: RecentProject[] = [
    { id: '1', name: "Pilgrim's Progress", progress: 45 },
    { id: '2', name: 'Mere Christianity', progress: 100 },
    { id: '3', name: 'Don Quixote', progress: 25 },
    { id: '5', name: 'The Cost of Discipleship', progress: 0 },
  ];

  recentActivity: ActivityItem[] = [
    { user: 'Ravi Kumaran', initials: 'RK', avatarBg: '#f43f5e', action: 'approved', target: 'P12', time: '2m ago' },
    { user: 'Deepa A.', initials: 'DA', avatarBg: '#10b981', action: 'requested review for', target: 'P45', time: '5m ago' },
    { user: 'Manoj R.', initials: 'MR', avatarBg: '#3b82f6', action: 'escalated', target: 'P78', time: '12m ago' },
    { user: 'System', initials: 'AI', avatarBg: '#64748b', action: 'translated', target: 'Chapter 2', time: '1h ago' },
  ];

  setMetric(metric: string) {
    this.throughputMetric = metric;
  }
}

<!-- Page Title Row -->
<div class="page-header-row">
  <div class="title-meta">
    <h1 class="page-title">Good morning, {{ userName }}</h1>
    <p class="page-subtitle">
      5 pages need your review · 3 escalations open · last sync {{ lastSync }}
    </p>
  </div>
  <p-button label="New project" icon="pi pi-plus" size="small" />
</div>

<div class="dashboard-container">

  <!-- ── Top Stats Row ──────────────────────────────────────── -->
  <div class="stats-grid">
    @for (s of stats; track s.label) {
      <p-card styleClass="tai-stat-card">
        <span class="tai-eyebrow">{{ s.label }}</span>
        <div class="stat-main">
          <span class="stat-value">{{ s.value }}</span>
        </div>
        <div class="stat-delta" [class.up]="s.deltaUp" [class.down]="!s.deltaUp">
          <i class="pi" [class.pi-arrow-up]="s.deltaUp" [class.pi-arrow-down]="!s.deltaUp"></i>
          <span class="delta-val">{{ s.delta }}</span>
          <span class="delta-label">{{ s.deltaLabel }}</span>
        </div>
      </p-card>
    }
  </div>

  <!-- ── Middle Row: Throughput + My Queue ──────────────────── -->
  <div class="content-grid">
    
    <!-- Throughput Chart Card -->
    <p-card styleClass="tai-chart-card">
      <div class="card-header">
        <span class="card-title">Throughput · last 12 weeks</span>
        <div class="metric-toggle">
          <button 
            [class.active]="throughputMetric === 'Pages'" 
            (click)="setMetric('Pages')">Pages</button>
          <button 
            [class.active]="throughputMetric === 'Words'" 
            (click)="setMetric('Words')">Words</button>
        </div>
      </div>
      
      <div class="chart-canvas">
        <div class="bar-container">
          @for (h of throughputData; track $index) {
            <div class="bar-wrap">
              <div class="bar" [style.height.%]="h"></div>
            </div>
          }
        </div>
      </div>
      
      <div class="chart-footer">
        Total: {{ throughputTotal | number }} pages · 
        peak {{ throughputPeak }} · 
        avg {{ throughputAvg }}
      </div>
    </p-card>

    <!-- My Queue Card -->
    <p-card styleClass="tai-list-card">
      <div class="card-header">
        <span class="card-title">My queue</span>
        <a routerLink="/queue" class="view-all">View all →</a>
      </div>
      
      <div class="list-content">
        @for (item of queueItems; track item.id) {
          <div class="list-item queue-item" [routerLink]="['/review', item.id]">
            <div class="queue-main">
              <p-tag styleClass="tai-dot approved" />
              <span class="page-num">{{ item.page }}</span>
              <span class="dot-sep">·</span>
              <span class="project-name">{{ item.project }}</span>
            </div>
            <div class="queue-meta">
              <span class="err-count">{{ item.errors }}err</span>
              <p-tag [value]="item.priority" [severity]="item.prioritySeverity" styleClass="priority-tag" />
            </div>
          </div>
        }
      </div>
    </p-card>

  </div>

  <!-- ── Bottom Row: Recent Projects + Recent Activity ──────── -->
  <div class="content-grid">

    <!-- Recent Projects Card -->
    <p-card styleClass="tai-list-card">
      <div class="card-header">
        <span class="card-title">Recent projects</span>
        <a routerLink="/projects" class="view-all">View all →</a>
      </div>
      
      <div class="list-content">
        @for (p of recentProjects; track p.id) {
          <div class="list-item project-row" [routerLink]="['/projects', p.id]">
            <span class="project-name">{{ p.name }}</span>
            <div class="progress-wrap">
              <p-progressBar [value]="p.progress" [showValue]="false" styleClass="mini-bar" />
              <span class="progress-pct">{{ p.progress }}%</span>
            </div>
          </div>
        }
      </div>
    </p-card>

    <!-- Recent Activity Card -->
    <p-card styleClass="tai-list-card">
      <div class="card-header">
        <span class="card-title">Recent activity</span>
        <a class="view-all">View all →</a>
      </div>
      
      <div class="list-content">
        @for (act of recentActivity; track $index) {
          <div class="list-item activity-item">
            <p-avatar 
              [label]="act.initials" 
              shape="circle" 
              [style]="{'background-color': act.avatarBg, 'color': '#fff'}" 
              styleClass="activity-avatar"
            />
            <div class="activity-text">
              <span class="user">{{ act.user }}</span>
              <span class="action"> {{ act.action }} </span>
              <span class="target">{{ act.target }}</span>
              <span class="time">{{ act.time }}</span>
            </div>
          </div>
        }
      </div>
    </p-card>

  </div>
</div>

// Claude designs/TranslationAI/screens/dashboard.jsx
// ============================================================
// Dashboard
// ============================================================

const Dashboard = ({ onNavigate }) => {
  const { PROJECTS, ACTIVITY, TEAM, QUEUE, WEEKLY_PAGES } = window.tAIData;

  return (
    <div className="page fade-in">
      <div className="page-header">
        <div>
          <h1 className="page-title">Good morning, Ravi</h1>
          <p className="page-subtitle">5 pages need your review · 3 escalations open · last sync 2 min ago</p>
        </div>
        <div className="row">
          <Btn icon="download">Export weekly</Btn>
          <Btn kind="primary" icon="plus" onClick={() => onNavigate("projects")}>New project</Btn>
        </div>
      </div>

      <div className="grid grid--4" style={{ marginBottom: "var(--sp-6)" }}>
        <div className="card">
          <div className="stat">
            <div className="stat__label">Active projects</div>
            <div className="stat__value tabnums">12</div>
            <div className="stat__delta"><Icon name="arrowUp" size={12}/> +2 this month</div>
          </div>
        </div>
        <div className="card">
          <div className="stat">
            <div className="stat__label">Pages translated</div>
            <div className="stat__value tabnums">1,240</div>
            <div className="stat__delta"><Icon name="arrowUp" size={12}/> 132 this week</div>
          </div>
        </div>
        <div className="card">
          <div className="stat">
            <div className="stat__label">Pending review</div>
            <div className="stat__value tabnums" style={{ color: "var(--warning)" }}>350</div>
            <div className="stat__delta stat__delta--down"><Icon name="arrowUp" size={12} style={{transform:"rotate(180deg)"}}/> −18 since Mon</div>
          </div>
        </div>
        <div className="card">
          <div className="stat">
            <div className="stat__label">Avg quality</div>
            <div className="stat__value tabnums" style={{ color: "var(--success)" }}>82%</div>
            <div className="stat__delta"><Icon name="arrowUp" size={12}/> +4pts</div>
          </div>
        </div>
      </div>

      <div className="grid grid--2">
        <div className="card">
          <div className="card-header">
            <h3 className="card-title">Throughput · last 12 weeks</h3>
            <div className="row" style={{ gap: 6 }}>
              <Pill>Pages</Pill>
              <Pill kind="default">Words</Pill>
            </div>
          </div>
          <div className="bar-chart">
            {WEEKLY_PAGES.map((v, i) => (
              <div key={i} className="bar-chart__bar" style={{ height: `${(v / 132) * 100}%`, opacity: 0.4 + (i / WEEKLY_PAGES.length) * 0.6 }} title={`Week ${i + 1}: ${v} pages`}>
                {i === WEEKLY_PAGES.length - 1 && <span className="bar-chart__label">w{i+1}</span>}
                {i === 0 && <span className="bar-chart__label">w1</span>}
              </div>
            ))}
          </div>
          <div className="row row--between" style={{ marginTop: 28, fontSize: 12, color: "var(--text-3)" }}>
            <span>Total: 1,061 pages</span>
            <span className="mono">peak 132 · avg 88</span>
          </div>
        </div>

        <div className="card">
          <div className="card-header">
            <h3 className="card-title">My queue</h3>
            <Btn kind="ghost" size="sm" onClick={() => onNavigate("queue")}>View all <Icon name="arrowRight" size={12}/></Btn>
          </div>
          <div className="col" style={{ gap: 0 }}>
            {QUEUE.slice(0, 5).map((q) => (
              <button key={q.id} onClick={() => onNavigate("review")} className="page-pill" style={{ justifyContent: "space-between", padding: "10px 12px" }}>
                <span className="row">
                  <StatusDot status={q.status} />
                  <span style={{ color: "var(--text)", fontWeight: 500 }}>{q.page}</span>
                  <span className="dim">·</span>
                  <span className="muted ellipsis" style={{maxWidth: 140}}>{q.project}</span>
                </span>
                <span className="row" style={{ gap: 8 }}>
                  <span className="tag">{q.errors} err</span>
                  <PriorityPill level={q.priority} />
                </span>
              </button>
            ))}
          </div>
        </div>

        <div className="card">
          <div className="card-header">
            <h3 className="card-title">Recent projects</h3>
            <Btn kind="ghost" size="sm" onClick={() => onNavigate("projects")}>View all <Icon name="arrowRight" size={12}/></Btn>
          </div>
          <div className="col" style={{ gap: 14 }}>
            {PROJECTS.slice(0, 4).map((p) => (
              <div key={p.id} onClick={() => onNavigate("projectDetail", p)} style={{ cursor: "pointer" }}>
                <div className="row row--between" style={{ marginBottom: 6 }}>
                  <span style={{ fontWeight: 500 }}>{p.name}</span>
                  <span className="mono dim">{p.progress}%</span>
                </div>
                <Progress value={p.progress} kind={p.progress === 100 ? "success" : null} />
              </div>
            ))}
          </div>
        </div>

        <div className="card">
          <div className="card-header">
            <h3 className="card-title">Recent activity</h3>
            <Btn kind="ghost" size="sm">View all <Icon name="arrowRight" size={12}/></Btn>
          </div>
          <div>
            {ACTIVITY.map((a, i) => (
              <div key={i} className="activity-item">
                <Avatar initials={a.initials} color={a.color} />
                <div style={{ flex: 1, minWidth: 0 }}>
                  <div><strong>{a.user}</strong> <span className="muted">{a.action}</span> {a.target}</div>
                  <div className="activity-item__time">{a.time} ago</div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
};

window.Dashboard = Dashboard;
